spring:
  application:
     name: DataCollection-Application
  
  datasource:
    username: root
    password: Admin@123
    url: jdbc:mysql://localhost:3306/RealTimeProjectDC?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  main:
    allow-bean-definition-overriding: true
  
  boot:
    admin:
      client:
        url: http://localhost:1111/  # URL where Spring Boot Admin server is running    
eureka:
    client:
     service-url:
       defaultZone: http://localhost:8761/eureka    
     register-with-eureka: true        # Registers this service with Eureka
     fetch-registry: true              # Enables this service to fetch registry from Eureka
  
management:
   endpoints:
     web:
       exposure:
         include: '*'  # Expose all management endpoints    

server:
  port: 9595   